#!/usr/bin/env bash

progress-bar() {
  local current=$1
  local no_of_files=$2

  local length=60
  local percent_done=$((current * 100 / no_of_files))
  local num_bars=$((percent_done * length / 100))

#  echo "Processing $current/$no_of_files ($percent_done%)"

  local i
  local s='['
  for ((i = 0; i < num_bars; i++)); do
    s+='|'
  done
  for ((i = num_bars; i < length; i++)); do
    s+=' '
  done
  s+=']'

  echo -ne "$s $current/$no_of_files ($percent_done%)\r"
}

shopt -s globstar nullglob

echo 'finding files'

files=(./**/*cache)
len=${#files[@]}

echo "found $len files"

i=0
for file in "${files[@]}"; do
  progress-bar "$((i+1))" "$len"
  ((i++))
done

echo