#!/usr/bin/env bash

progress-bar() {
  local current=$1
  local no_of_files=$2
  local length=$3

  local bar_char='|'
  local empty_char=' '
  local percent_done=$((current * 100 / no_of_files))
  local num_bars=$((percent_done * length / 100))

#  echo "Processing $current/$no_of_files ($percent_done%)"

  local i
  local s='['
  for ((i = 0; i < num_bars; i++)); do
    s+=$bar_char
  done
  for ((i = num_bars; i < length; i++)); do
    s+=$empty_char
  done
  s+=']'

  echo -ne "$s $current/$no_of_files ($percent_done%)\r"
}

process-file() {
  local file=$1

  sleep .01
}

shopt -s globstar nullglob

echo 'finding files'

files=(./**/*cache)
len=${#files[@]}

echo "found $len files"

i=0
for file in "${files[@]}"; do
  progress-bar "$((i+1))" "$len" "60"
  process-file "$file"
  ((i++))
done

echo